### ISSUE TITLE
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs Module build failed: Error: ENOENT: no such file or directory, open '/Users/penalozajohn25/proyectos/AISA/jakue_panel/node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs'

### ISSUE THREAD

**Issue by penalozajohn25** [leNicDev/ng-hcaptcha#68] opened 2023-08-18 13:53 UTC

**Comment by leNicDev** [comment] 2024-01-04 17:00
Duplicate of #69

**Closed by leNicDev** 2024-01-04 17:00 UTC
Labels: duplicate
